---

- name: Run show commands on routers
  hosts: 192.168.100.1
  gather_facts: false


  vars_prompt:
    - name: "ansible_ssh_pass"
      prompt: "Enter pass"


  tasks:

    - name: Check pass 1
      expect:
        command: ssh cisco@192.168.100.1
        responses:
          Password: "{{ansible_ssh_pass}}"
          '[#>]': exit
      delegate_to: localhost
      ignore_errors: yes

    - name: 
      set_fact:
        ansible_ssh_pass: cisco

    - name: Check pass 2
      expect:
        command: ssh cisco@192.168.100.1
        responses:
          Password: "{{ansible_ssh_pass}}"
          '[#>]': exit
      delegate_to: localhost



    - name: run sh clock
      raw: sh clock


