---

- name: Run show commands on routers
  hosts: 192.168.100.1
  gather_facts: false

  tasks:

    - name: run show commands
      telnet:
        user: cisco
        password: cisco
        login_prompt: "Username: "
        prompts:
          - "[>|#]"
        command:
          - terminal length 0
          - show version

